[tool.poetry]
name = "rebasebranches"
version = "0.1.0"
description = ""
authors = ["jayanth <jayanthzlak@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

# child1
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
